### ISSUE TITLE
Example with Port. An error with my test

### ISSUE THREAD

**Issue by nlamirault** [louy/terraform-provider-uptimerobot#16] opened 2019-02-06 08:44 UTC
could you provides an example using port monitoring ?
I try : 

```
resource "uptimerobot_monitor" "kubernetes_master" {
  url           = "tcp:/my.example.com:5555"
  type          = "port"
  sub_type      = "custom"
  port          = "5555"
  friendly_name = "An example"
}
```

```
resource "uptimerobot_monitor" "kubernetes_master" {
  url           = "my.example.com"
  type          = "port"
  sub_type      = "custom"
  port          = "5555"
  friendly_name = "An example"
}
```

I've got this error : 

```
Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


panic: interface conversion: interface {} is string, not int
2019-02-06T09:44:15.866+0100 [DEBUG] plugin.terraform-provider-uptimerobot: 
2019-02-06T09:44:15.866+0100 [DEBUG] plugin.terraform-provider-uptimerobot: goroutine 32 [running]:
2019-02-06T09:44:15.866+0100 [DEBUG] plugin.terraform-provider-uptimerobot: github.com/louy/terraform-provider-uptimerobot/uptimerobot.resourceMonitorCreate(0xc0001edf10, 0xe0d960, 0xc0004b6e60, 0xc0001edf10, 0x0)
2019-02-06T09:44:15.866+0100 [DEBUG] plugin.terraform-provider-uptimerobot: 	/home/nlamirault/Projects/terraform-provider-uptimerobot/uptimerobot/resource_uptimerobot_monitor.go:115 +0xa25
2019-02-06T09:44:15.866+0100 [DEBUG] plugin.terraform-provider-uptimerobot: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc0001ed1f0, 0xc00038c6e0, 0xc00001d320, 0xe0d960, 0xc0004b6e60, 0x40d601, 0xc000519b80, 0x4c3d7c)
2019-02-06T09:44:15.866+0100 [DEBUG] plugin.terraform-provider-uptimerobot: 	/home/nlamirault/Applications/golang/pkg/mod/github.com/hashicorp/terraform@v0.11.7/helper/schema/resource.go:227 +0x351
2019-02-06T09:44:15.866+0100 [DEBUG] plugin.terraform-provider-uptimerobot: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0001ed2d0, 0xc00038c690, 0xc00038c6e0, 0xc00001d320, 0xc00005aa80, 0x18, 0x7f0cce5b86c0)
2019-02-06T09:44:15.866+0100 [DEBUG] plugin.terraform-provider-uptimerobot: 	/home/nlamirault/Applications/golang/pkg/mod/github.com/hashicorp/terraform@v0.11.7/helper/schema/provider.go:283 +0x9c
2019-02-06T09:44:15.866+0100 [DEBUG] plugin.terraform-provider-uptimerobot: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc00001c640, 0xc00001cee0, 0xc0002c9480, 0x0, 0x0)
2019-02-06T09:44:15.866+0100 [DEBUG] plugin.terraform-provider-uptimerobot: 	/home/nlamirault/Applications/golang/pkg/mod/github.com/hashicorp/terraform@v0.11.7/plugin/resource_provider.go:527 +0x57
2019-02-06T09:44:15.866+0100 [DEBUG] plugin.terraform-provider-uptimerobot: reflect.Value.call(0xc0003844e0, 0xc0001746f8, 0x13, 0xe4354b, 0x4, 0xc000519f18, 0x3, 0x3, 0xc000181980, 0x414fe7, ...)
2019-02-06T09:44:15.866+0100 [DEBUG] plugin.terraform-provider-uptimerobot: 	/home/nlamirault/Applications/go/src/reflect/value.go:447 +0x454
2019-02-06T09:44:15.866+0100 [DEBUG] plugin.terraform-provider-uptimerobot: reflect.Value.Call(0xc0003844e0, 0xc0001746f8, 0x13, 0xc000365f18, 0x3, 0x3, 0x12a05f200, 0xc000365f10, 0xc000365fb8)
2019-02-06T09:44:15.866+0100 [DEBUG] plugin.terraform-provider-uptimerobot: 	/home/nlamirault/Applications/go/src/reflect/value.go:308 +0xa4
2019-02-06T09:44:15.866+0100 [DEBUG] plugin.terraform-provider-uptimerobot: net/rpc.(*service).call(0xc00049a800, 0xc00038c4b0, 0xc000212cf8, 0xc000212d10, 0xc00039c580, 0xc000438580, 0xcacd40, 0xc00001cee0, 0x16, 0xcacd80, ...)
2019-02-06T09:44:15.866+0100 [DEBUG] plugin.terraform-provider-uptimerobot: 	/home/nlamirault/Applications/go/src/net/rpc/server.go:384 +0x14e
2019-02-06T09:44:15.866+0100 [DEBUG] plugin.terraform-provider-uptimerobot: created by net/rpc.(*Server).ServeCodec
2019-02-06T09:44:15.866+0100 [DEBUG] plugin.terraform-provider-uptimerobot: 	/home/nlamirault/Applications/go/src/net/rpc/server.go:481 +0x47e
2019-02-06T09:44:15.867+0100 [DEBUG] plugin: plugin process exited: path=/home/nlamirault/.terraform.d/plugins/linux_amd64/terraform-provider-uptimerobot
2019/02/06 09:44:15 [TRACE] root: eval: *terraform.EvalWriteState
2019/02/06 09:44:15 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2019/02/06 09:44:15 [TRACE] root: eval: *terraform.EvalIf
2019/02/06 09:44:15 [TRACE] root: eval: *terraform.EvalWriteState
2019/02/06 09:44:15 [TRACE] root: eval: *terraform.EvalWriteDiff
2019/02/06 09:44:15 [TRACE] root: eval: *terraform.EvalApplyPost
2019/02/06 09:44:15 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* uptimerobot_monitor.kubernetes_master: unexpected EOF
2019/02/06 09:44:15 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* uptimerobot_monitor.kubernetes_master: unexpected EOF
2019/02/06 09:44:15 [TRACE] [walkApply] Exiting eval tree: uptimerobot_monitor.kubernetes_master
2019/02/06 09:44:15 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2019/02/06 09:44:15 [TRACE] dag/walk: upstream errored, not walking "provider.uptimerobot (close)"
2019/02/06 09:44:15 [TRACE] dag/walk: upstream errored, not walking "root"
2019/02/06 09:44:15 [TRACE] Preserving existing state lineage "04a4a4b1-6432-89b5-083f-72a0cf33f934"
2019/02/06 09:44:15 [TRACE] Preserving existing state lineage "04a4a4b1-6432-89b5-083f-72a0cf33f934"
2019/02/06 09:44:15 [TRACE] Preserving existing state lineage "04a4a4b1-6432-89b5-083f-72a0cf33f934"
2019/02/06 09:44:15 [TRACE] Preserving existing state lineage "04a4a4b1-6432-89b5-083f-72a0cf33f934"
2019/02/06 09:44:15 [DEBUG] plugin: waiting for all plugin processes to complete...

```

**Comment by louy** [comment] 2019-02-21 21:37
This looks like a bug. Sadly there's no test for the port option for some reason so I'll add one when I get a chance.

The issue is that [port is defined as a String](https://github.com/louy/terraform-provider-uptimerobot/blob/3cf611e/uptimerobot/resource_uptimerobot_monitor.go#L44) whereas it should've been an Int in the TF provider

I'll fix this. Thanks for reporting

**Comment by louy** [comment] 2019-02-21 21:52
Once #17 is merged your code should work just fine :)

**Closed** 2019-02-21 21:58 UTC

**Comment by louy** [comment] 2019-08-20 12:30
@all-contributors please add @nlamirault for bug
